cfl_test.cc:  Add missing include for std::array.
This fixes errors like the following on Visual studio builds on windows:

```
C:\src\avm\test\cfl_test.cc(888,35): error C2079: 'chroma_above_left_line_pairs' uses undefined class 'std::array<std::array<int,2>,3>' [C:\src\mybuild\test_avm_common.vcxproj]
C:\src\avm\test\cfl_test.cc(892,35): error C2079: 'luma_above_left_line_pairs' uses undefined class 'std::array<std::array<int,2>,3>' [C:\src\mybuild\test_avm_common.vcxproj]
C:\src\avm\test\cfl_test.cc(912,24): error C2079: 'arrlin' uses undefined class 'std::array<int,2>' [C:\src\mybuild\test_avm_common.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\include\tuple(151,9): error C2079: 'std::_Tuple_val<_This>::_Val' uses undefined class 'std::array<int,2>' [C:\src\mybuild\tes
t_avm_common.vcxproj]
```